# Generated by Django 4.2.6 on 2024-02-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
    ]
