# Generated by Django 5.0.1 on 2024-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.BigIntegerField(default='00000', max_length=6),
        ),
    ]
