# Generated by Django 5.0.1 on 2024-06-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Wallet_balance',
            new_name='wallet_balance',
        ),
    ]
