# Generated by Django 5.0.1 on 2024-06-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_wallet_balance_wallet_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
