# Generated by Django 5.0.1 on 2024-06-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
