# Generated by Django 5.0.1 on 2024-02-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='Category_description',
        ),
    ]
