# Generated by Django 4.2.6 on 2024-02-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_description_category_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_description',
            new_name='category_description',
        ),
    ]
