# Generated by Django 5.0.1 on 2024-05-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ip'),
        ('orders', 'XXXX_auto_populate_order_number'),
    ]

    operations = [
    ]
