# Generated by Django 4.2.6 on 2024-02-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_description_category_category_description'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
